
CREATE TABLE IF NOT EXISTS vehicles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ownerSerial VARCHAR(255) NOT NULL,
  model INT NOT NULL,
  vin VARCHAR(64),
  regNumber VARCHAR(32),
  brand VARCHAR(64),
  modelName VARCHAR(64),
  mass DOUBLE DEFAULT 0,
  engine TEXT,
  gearbox TEXT,
  fuelType VARCHAR(16),
  fuel DOUBLE DEFAULT 0,
  fluids TEXT,
  wear TEXT,
  setups TEXT,
  ecustate TEXT,
  mileage DOUBLE DEFAULT 0,
  odometer DOUBLE DEFAULT 0,
  insurance TEXT,
  inspection TEXT,
  extra TEXT,
  posX DOUBLE, posY DOUBLE, posZ DOUBLE,
  rotX DOUBLE, rotY DOUBLE, rotZ DOUBLE,
  isSpawned TINYINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
